// AUTO-GENERATED. Do not edit directly.
// Generated by scripts/generate-ts.ts

export interface LoruConfigLibItem {
  name: string;
  // Library/package name.
  path: string;
  // Relative path to the library root.
  kind: string;
  // Library type for publishing.
  publish?: string | undefined;
  // Publish target (e.g., jsr, crates.io).
}

export interface LoruConfigMeta {
  schema_version?: string | undefined;
  // Default schema version for entries (semver or range).
}

export interface LoruConfigWorkspace {
  members?: string[] | undefined;
  // Paths to member projects included in this workspace.
}

export interface LoruConfigPluginItem {
  id: string;
  // Unique slug for the plugin (lowercase, kebab-case).
  name: string;
  // Human-readable name for the plugin.
  path?: string | undefined;
  // Relative path to the plugin project root.
  entrypoint?: string | undefined;
  // Path to the plugin entry module.
  schema_version?: string | undefined;
  // Schema version/range to validate this plugin metadata.
}

export interface LoruConfigPageItem {
  id: string;
  // Unique slug for the tenant/page (lowercase, kebab-case).
  name: string;
  // Display name for the tenant/page.
  path?: string | undefined;
  // Relative path to the tenant project root.
  entrypoint?: string | undefined;
  // Entry module for this tenant/page.
  schema_version?: string | undefined;
  // Schema version/range to validate this tenant metadata.
  domains?: string[] | undefined;
  // Primary domains associated with this tenant/page.
  locales?: string[] | undefined;
  // Supported locales.
}

export interface LoruConfigTaskItem {
  name: string;
  // Task name invoked via `loru run <name>`.
  description?: string | undefined;
  // What this task does.
  cmd?: string | undefined;
  // Default command to run (shell).
  platform?: Record<string, unknown> | undefined;
  // Platform-specific overrides.
}

export interface LoruConfigBuildItem {
  name?: string | undefined;
  // Optional label for this build step.
  phase: string;
  // Build lifecycle phase.
  targets?: string[] | undefined;
  // Optional list of plugin/page/lib identifiers this step applies to.
  cmd?: string | undefined;
  // Default command to run for this phase.
  platform?: Record<string, unknown> | undefined;
  // Platform-specific overrides.
}

export interface LoruConfig {
  lib?: LoruConfigLibItem[] | undefined;
  // Libraries/packages within this workspace that can be published.
  meta?: LoruConfigMeta | undefined;
  workspace?: LoruConfigWorkspace | undefined;
  plugin?: LoruConfigPluginItem[] | undefined;
  // Plugin entries in this workspace/project.
  page?: LoruConfigPageItem[] | undefined;
  // Tenant/page entries in this workspace/project.
  task?: LoruConfigTaskItem[] | undefined;
  // Custom tasks available in this workspace or project.
  build?: LoruConfigBuildItem[] | undefined;
  // Build pipeline tasks with explicit phases.
}

