// AUTO-GENERATED. Do not edit directly.
// Generated by scripts/generate-ts.ts

export interface LoruConfigLibItem {
  name: string;
  // Library/package name.
  path?: string | undefined;
  // Relative path to the library root.
  kind?: "deno" | "rust" | "auto" | undefined;
  // Library type for publishing (auto detects Cargo.toml vs deno.json).
  publish?: string | undefined;
  // Publish target (e.g., jsr, crates.io).
}

export interface LoruConfigMeta {
  schema_version?: string | undefined;
  // Default schema version for entries (semver or range).
}

export interface LoruConfigWorkspace {
  members?: string[] | undefined;
  // Paths to member projects included in this workspace.
}

export interface LoruConfigPluginItem {
  id: string;
  // Unique slug for the plugin (lowercase, kebab-case).
  name: string;
  // Human-readable name for the plugin.
  path?: string | undefined;
  // Relative path to the plugin project root.
  kind?: "deno" | "rust" | "auto" | undefined;
  // Plugin implementation type (auto detects Cargo.toml vs deno.json).
  entrypoint?: string | undefined;
  // Path to the plugin entry module.
  schema_version?: string | undefined;
  // Schema version/range to validate this plugin metadata.
}

export interface LoruConfigPageItem {
  id: string;
  // Unique slug for the tenant/page (lowercase, kebab-case).
  name: string;
  // Display name for the tenant/page.
  path?: string | undefined;
  // Relative path to the tenant project root.
  kind?: "deno" | "rust" | "auto" | undefined;
  // Tenant implementation type (auto detects Cargo.toml vs deno.json).
  entrypoint?: string | undefined;
  // Entry module for this tenant/page.
  schema_version?: string | undefined;
  // Schema version/range to validate this tenant metadata.
  domains?: string[] | undefined;
  // Primary domains associated with this tenant/page.
  locales?: string[] | undefined;
  // Supported locales.
}

export interface LoruConfigBinItem {
  name: string;
  // Binary name (used for tagging and task targeting).
  id?: string | undefined;
  // Optional explicit ID for the binary (defaults to name).
  path?: string | undefined;
  // Relative path to the binary project root.
  kind?: "deno" | "rust" | "auto" | undefined;
  // Binary implementation type (auto detects Cargo.toml vs deno.json).
  entrypoint?: string | undefined;
  // Entry module for Deno binaries.
  schema_version?: string | undefined;
  // Schema version/range to validate this binary metadata.
}

export interface LoruConfigTaskItem {
  name: string;
  // Task name invoked via `loru run <name>`.
  description?: string | undefined;
  // What this task does.
  cmd?: string | undefined;
  // Default command to run (shell).
  platform?: Record<string, unknown> | undefined;
  // Platform-specific overrides.
}

export interface LoruConfigCheck {
  artifacts?: PipelineArtifacts | undefined;
  task?: CheckTask[] | undefined;
  // Check pipeline hooks that run with loru dev check (fmt/lint/type-check/test).
}

export interface LoruConfigBuild {
  artifacts?: PipelineArtifacts | undefined;
  task?: BuildTask[] | undefined;
  // Build pipeline tasks with explicit phases.
}

export interface LoruConfig {
  lib?: LoruConfigLibItem[] | undefined;
  // Libraries/packages within this workspace that can be published.
  meta?: LoruConfigMeta | undefined;
  workspace?: LoruConfigWorkspace | undefined;
  plugin?: LoruConfigPluginItem[] | undefined;
  // Plugin entries in this workspace/project.
  page?: LoruConfigPageItem[] | undefined;
  // Tenant/page entries in this workspace/project.
  bin?: LoruConfigBinItem[] | undefined;
  // Binary targets within this workspace/project.
  deno?: unknown | undefined;
  // Optional inline Deno config; written to generated deno.json when running via loru.
  cargo?: unknown | undefined;
  // Optional inline Cargo manifest; written to generated Cargo.toml when running via loru.
  task?: LoruConfigTaskItem[] | undefined;
  // Custom tasks available in this workspace or project.
  check?: LoruConfigCheck | undefined;
  // Check pipeline configuration.
  build?: LoruConfigBuild | undefined;
  // Build pipeline configuration.
}

export interface DenoConfig {
  [key: string]: unknown;
}

export interface CargoConfig {
  [key: string]: unknown;
}

export interface PipelineArtifacts {
  scope?: "workspace" | "project" | "custom" | undefined;
  // Where artifacts should live: workspace root, project root, or a custom path.
  path?: string | undefined;
  // Custom base path for artifacts (absolute or relative to project).
  dirname?: string | undefined;
  // Subdirectory template under artifact base (supports @tool and @tool-target tokens).
}

export interface PipelineStepBase {
  name?: string | undefined;
  // Optional label for this pipeline step.
  description?: string | undefined;
  // Optional human-friendly description of the step.
  targets?: string[] | undefined;
  // Optional list of plugin/page/lib identifiers this step applies to.
  cmd?: string | undefined;
  // Default command to run for this step.
  platform?: Record<string, unknown> | undefined;
  // Platform-specific overrides.
}

export interface CheckTask extends PipelineStepBase {
  name?: string | undefined;
  // Optional label for this pipeline step.
  description?: string | undefined;
  // Optional human-friendly description of the step.
  targets?: string[] | undefined;
  // Optional list of plugin/page/lib identifiers this step applies to.
  cmd?: string | undefined;
  // Default command to run for this step.
  platform?: Record<string, unknown> | undefined;
  // Platform-specific overrides.
  stage: "precheck" | "fmt" | "lint" | "check" | "test" | "postcheck";
  // Check pipeline stage for this step.
}

export interface BuildTask extends PipelineStepBase {
  name?: string | undefined;
  // Optional label for this pipeline step.
  description?: string | undefined;
  // Optional human-friendly description of the step.
  targets?: string[] | undefined;
  // Optional list of plugin/page/lib identifiers this step applies to.
  cmd?: string | undefined;
  // Default command to run for this step.
  platform?: Record<string, unknown> | undefined;
  // Platform-specific overrides.
  phase: "prebuild" | "build" | "postbuild" | "prerelease" | "postrelease";
  // Build lifecycle phase.
}

export interface PipelineStep extends PipelineStepBase {}
export interface PipelineStepCheck extends CheckTask {}
export interface PipelineStepBuild extends BuildTask {}
