// AUTO-GENERATED. Do not edit directly.
// Generated by scripts/generate-rust.ts

use std::collections::HashMap;
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PluginMetadata {
    /// Unique slug for the plugin (lowercase, kebab-case).
    pub id: String,
    /// Human-readable name for the plugin.
    pub name: String,
    /// Plugin version in semver format.
    pub version: Option<String>,
    /// Short description of what the plugin does.
    pub description: Option<String>,
    /// Plugin author or maintainer.
    pub author: Option<String>,
    /// License identifier (SPDX).
    pub license: Option<String>,
    /// Template version/tag this plugin was scaffolded from.
    #[serde(rename = "template_version")]
    pub template_version: Option<String>,
    /// Path to the plugin entry module.
    pub entry: Option<String>,
    /// Capabilities the plugin requests.
    pub permissions: Option<Vec<String>>,
    /// Free-form labels for categorization.
    pub tags: Option<Vec<String>>,
    /// Plugin-specific configuration values.
    pub config: Option<std::collections::HashMap<String, serde_json::Value>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct TenantMetadataPluginsItem {
    /// Plugin slug.
    pub id: String,
    /// Pinned version or semver range.
    pub version: Option<String>,
    /// Whether the plugin is enabled.
    pub enabled: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct TenantMetadata {
    /// Unique slug for the tenant (lowercase, kebab-case).
    pub id: String,
    /// Display name for the tenant.
    pub name: String,
    /// Primary domains associated with this tenant.
    pub domains: Option<Vec<String>>,
    /// Default locale for content and UI.
    #[serde(rename = "default_locale")]
    pub default_locale: Option<String>,
    /// Additional supported locales.
    pub locales: Option<Vec<String>>,
    /// Plugins enabled for this tenant.
    pub plugins: Option<Vec<TenantMetadataPluginsItem>>,
    /// Template version/tag this tenant was scaffolded from.
    #[serde(rename = "template_version")]
    pub template_version: Option<String>,
}
