// AUTO-GENERATED. Do not edit directly.
// Generated by scripts/generate-rust.ts

use std::collections::HashMap;
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoruConfigMeta {
    /// Default schema version for entries (semver or range).
    #[serde(rename = "schema_version")]
    pub schema_version: Option<String>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoruConfigWorkspace {
    /// Paths to member projects included in this workspace.
    pub members: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoruConfigPluginItem {
    /// Unique slug for the plugin (lowercase, kebab-case).
    pub id: String,
    /// Human-readable name for the plugin.
    pub name: String,
    /// Relative path to the plugin project root.
    pub path: Option<String>,
    /// Path to the plugin entry module.
    pub entrypoint: Option<String>,
    /// Schema version/range to validate this plugin metadata.
    #[serde(rename = "schema_version")]
    pub schema_version: Option<String>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoruConfigPageItem {
    /// Unique slug for the tenant/page (lowercase, kebab-case).
    pub id: String,
    /// Display name for the tenant/page.
    pub name: String,
    /// Relative path to the tenant project root.
    pub path: Option<String>,
    /// Entry module for this tenant/page.
    pub entrypoint: Option<String>,
    /// Schema version/range to validate this tenant metadata.
    #[serde(rename = "schema_version")]
    pub schema_version: Option<String>,
    /// Primary domains associated with this tenant/page.
    pub domains: Option<Vec<String>>,
    /// Supported locales.
    pub locales: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoruConfig {
    pub meta: Option<LoruConfigMeta>,
    pub workspace: Option<LoruConfigWorkspace>,
    /// Plugin entries in this workspace/project.
    pub plugin: Option<Vec<LoruConfigPluginItem>>,
    /// Tenant/page entries in this workspace/project.
    pub page: Option<Vec<LoruConfigPageItem>>,
}

