// AUTO-GENERATED. Do not edit directly.
// Generated by scripts/generate-rust.ts

use serde_json::Value;
use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoruConfigLibItem {
    /// Library/package name.
    pub name: String,
    /// Relative path to the library root.
    pub path: String,
    /// Library type for publishing.
    pub kind: String,
    /// Publish target (e.g., jsr, crates.io).
    pub publish: Option<String>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoruConfigMeta {
    /// Default schema version for entries (semver or range).
    #[serde(rename = "schema_version")]
    pub schema_version: Option<String>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoruConfigWorkspace {
    /// Paths to member projects included in this workspace.
    pub members: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoruConfigPluginItem {
    /// Unique slug for the plugin (lowercase, kebab-case).
    pub id: String,
    /// Human-readable name for the plugin.
    pub name: String,
    /// Relative path to the plugin project root.
    pub path: Option<String>,
    /// Path to the plugin entry module.
    pub entrypoint: Option<String>,
    /// Schema version/range to validate this plugin metadata.
    #[serde(rename = "schema_version")]
    pub schema_version: Option<String>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoruConfigPageItem {
    /// Unique slug for the tenant/page (lowercase, kebab-case).
    pub id: String,
    /// Display name for the tenant/page.
    pub name: String,
    /// Relative path to the tenant project root.
    pub path: Option<String>,
    /// Entry module for this tenant/page.
    pub entrypoint: Option<String>,
    /// Schema version/range to validate this tenant metadata.
    #[serde(rename = "schema_version")]
    pub schema_version: Option<String>,
    /// Primary domains associated with this tenant/page.
    pub domains: Option<Vec<String>>,
    /// Supported locales.
    pub locales: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoruConfigTaskItem {
    /// Task name invoked via `loru run <name>`.
    pub name: String,
    /// What this task does.
    pub description: Option<String>,
    /// Default command to run (shell).
    pub cmd: Option<String>,
    /// Platform-specific overrides.
    pub platform: Option<std::collections::HashMap<String, serde_json::Value>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoruConfigCheck {
    pub artifacts: PipelineArtifacts,
    /// Check pipeline hooks that run with loru dev check (fmt/lint/type-check/test).
    pub task: Option<Vec<CheckTask>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoruConfigBuild {
    pub artifacts: PipelineArtifacts,
    /// Build pipeline tasks with explicit phases.
    pub task: Option<Vec<BuildTask>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoruConfig {
    /// Libraries/packages within this workspace that can be published.
    pub lib: Option<Vec<LoruConfigLibItem>>,
    pub meta: Option<LoruConfigMeta>,
    pub workspace: Option<LoruConfigWorkspace>,
    /// Plugin entries in this workspace/project.
    pub plugin: Option<Vec<LoruConfigPluginItem>>,
    /// Tenant/page entries in this workspace/project.
    pub page: Option<Vec<LoruConfigPageItem>>,
    /// Custom tasks available in this workspace or project.
    pub task: Option<Vec<LoruConfigTaskItem>>,
    /// Check pipeline configuration.
    pub check: Option<LoruConfigCheck>,
    /// Build pipeline configuration.
    pub build: Option<LoruConfigBuild>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PipelineArtifacts {
    /// Where artifacts should live: workspace root, project root, or a custom path.
    pub scope: Option<String>,
    /// Custom base path for artifacts (absolute or relative to project).
    pub path: Option<String>,
    /// Subdirectory template under artifact base (supports @tool and @tool-target tokens).
    pub dirname: Option<String>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PipelineStepBase {
    /// Optional label for this pipeline step.
    pub name: Option<String>,
    /// Optional human-friendly description of the step.
    pub description: Option<String>,
    /// Optional list of plugin/page/lib identifiers this step applies to.
    pub targets: Option<Vec<String>>,
    /// Default command to run for this step.
    pub cmd: Option<String>,
    /// Platform-specific overrides.
    pub platform: Option<std::collections::HashMap<String, serde_json::Value>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CheckTask {
    /// Optional label for this pipeline step.
    pub name: Option<String>,
    /// Optional human-friendly description of the step.
    pub description: Option<String>,
    /// Optional list of plugin/page/lib identifiers this step applies to.
    pub targets: Option<Vec<String>>,
    /// Default command to run for this step.
    pub cmd: Option<String>,
    /// Platform-specific overrides.
    pub platform: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Check pipeline stage for this step.
    pub stage: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct BuildTask {
    /// Optional label for this pipeline step.
    pub name: Option<String>,
    /// Optional human-friendly description of the step.
    pub description: Option<String>,
    /// Optional list of plugin/page/lib identifiers this step applies to.
    pub targets: Option<Vec<String>>,
    /// Default command to run for this step.
    pub cmd: Option<String>,
    /// Platform-specific overrides.
    pub platform: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Build lifecycle phase.
    pub phase: String,
}

pub trait PipelineStep {
    fn name(&self) -> Option<&String>;
    fn targets(&self) -> Option<&Vec<String>>;
    fn cmd(&self) -> Option<&String>;
    fn platform(&self) -> Option<&HashMap<String, Value>>;
}

impl PipelineStep for PipelineStepBase {
    fn name(&self) -> Option<&String> {
        self.name.as_ref()
    }
    fn targets(&self) -> Option<&Vec<String>> {
        self.targets.as_ref()
    }
    fn cmd(&self) -> Option<&String> {
        self.cmd.as_ref()
    }
    fn platform(&self) -> Option<&HashMap<String, Value>> {
        self.platform.as_ref()
    }
}

impl PipelineStep for CheckTask {
    fn name(&self) -> Option<&String> {
        self.name.as_ref()
    }
    fn targets(&self) -> Option<&Vec<String>> {
        self.targets.as_ref()
    }
    fn cmd(&self) -> Option<&String> {
        self.cmd.as_ref()
    }
    fn platform(&self) -> Option<&HashMap<String, Value>> {
        self.platform.as_ref()
    }
}

impl PipelineStep for BuildTask {
    fn name(&self) -> Option<&String> {
        self.name.as_ref()
    }
    fn targets(&self) -> Option<&Vec<String>> {
        self.targets.as_ref()
    }
    fn cmd(&self) -> Option<&String> {
        self.cmd.as_ref()
    }
    fn platform(&self) -> Option<&HashMap<String, Value>> {
        self.platform.as_ref()
    }
}
